### PR TITLE
Line-wrapping, auto-formatting and pre-commit hooks

### LINKED ISSUE #46: Line wrapping for readability of long descriptions
Some of the descriptions for properties are very long but there is no line-wrapping on them, resulting very long lines of >400 character length in some cases, making the CIM more difficult to comprehend at a glance. I suggest for readability an good code style we break up the descriptions in a similar way to the following, from (automated tools like 'black' don;t seem to do this automaticallyeven when given a set line-length to enforce, sadly, unless there is already line breaking of some sort):

```python
    return {
    ...
        'properties': [
            ('coupling_cost', 'float', '0.1',
             'Coupling cost measures the overhead caused by coupling. This can include... [long description].'),
    ...
            ]
    }
```

to:

```python
    return {
    ...
        'properties': [
            (
                 'coupling_cost', 'float', '0.1',
                 'Coupling cost measures the overhead caused by coupling. '
                 'This can include... [long description] '
                 '[more long description] ... '
                 '[more long description] ... '
                 '[more long description].'
            ),
    ...
            ]
    }
```

where Python's implicit line joining inside parentheses ensures a single string is recognised as the description.

### LINKED ISSUE #47: Code auto-formatting with 'black' for consistency
I am keen to blast the codebase with 'black' to auto-format the Python modules in a consistent way, in particular because it will convert the CIM classes code to be less dense and therefore more readable. For example, if I run the command `black --line-length 79 platform_classes.py` to auto-format that file, the classes becomes easier to digest as demonstrated with the `machine` class which becomes:

```python
def machine():
    """A computer/system/platform/machine which is used for simulation."""
    return {
        "type": "class",
        "base": "platform.partition",
        "is_abstract": False,
        "pstr": ("{}", ("name",)),
        "is_document": True,
        "properties": [
            (
                "peak_performance",
                "shared.numeric",
                "0.1",
                "Total peak performance (RPeak in Top500 lingo)",
            ),
            (
                "linpack_performance",
                "shared.numeric",
                "0.1",
                "Linpack performance (RMax in Top500 lingo)",
            ),
        ],
    }
```
whereas at present it is hard to pick out the cardinality, etc.:

https://github.com/ES-DOC/esdoc-cim-v2-schema/blob/0b065120cce05ad30a84c8868059512e3f396a2f/platform_classes.py#L92-L108

### PR DESCRIPTION
**Pull request by sadielbartholomew**
1. Resolve #46 (see commits e6c10d5 and fd0bc2e) and resolve #47 (see first two commits and a trivial change in 92649e1).
2. In the process, add a `black` configuration file (d3df227) and configure pre-commit hooks, which all pass at the final commit of this PR, to enforce the same formatting at commit time (9ccaf6c).
3. When formatting the line-wrapping I barely looked at the text and yet I noticed a property description which was trivially wrong and in a confusing way, so I fixed that: see e0cc2e9.

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
@davidhassell, though most of this is trivial, you may wish to cast an eye over the manual part, the line-wrapping (commit fd0bc2e), in case I made any mistakes (just needs if anything eyeballing to check the wrapped lines end with a whitespace), and e0cc2e9 because even though it is a trivial and non-controversial change, that is one which changes the CIM (but in a very minor way).

**Comment by sadielbartholomew** [comment]
I am thinking I might add a basic GitHub Action to confirm the auto-formatting has been applied by running the pre-commit hooks in a workflow job. Will push a further commit to add that now.

**Comment by sadielbartholomew** [comment]
Seeing if I can trigger the Actions job initially via open-close, though it may be that this PR needs to be merged before it will recognise the Actions workflow and not tell us that CI "has not been set up" as shown above...

**Comment by davidhassell** [comment]
Just eye-balled https://github.com/ES-DOC/esdoc-cim-v2-schema/commit/fd0bc2ec3a54c9b626e3958d6024161c501c36a7 and https://github.com/ES-DOC/esdoc-cim-v2-schema/commit/e0cc2e94278d72e9172629b17ee36ea2fe223221 - both look good to me.

**Comment by sadielbartholomew** [comment]
Thanks @davidhassell, in that case I will merge this and tag version `2.2`!

**Pull request merged**
